name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: Lint, Test, and Typecheck
    timeout-minutes: 15
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20, 22, 24]

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint, Test, Typecheck
        run: yarn ci
